/** @type {import('tailwindcss').Config} */
// Ported verbatim from the old inline <script>tailwind.config</script> in
// templates/base.html so the built stylesheet is identical to what the CDN
// used to generate at runtime.
module.exports = {
  content: [
    "./templates/**/*.html",
    "./static/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#e0bfbf",
        "on-tertiary-fixed": "#241a00",
        "tertiary-fixed": "#ffe088",
        outline: "#8c7071",
        "inverse-primary": "#ffb3b5",
        "on-primary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed-variant": "#574500",
        "on-surface": "#1c1b1b",
        "secondary-fixed": "#e4e2de",
        "surface-variant": "#e5e2e1",
        error: "#ba1a1a",
        "surface-container-highest": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c3",
        "inverse-surface": "#313030",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4f3d00",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1c1b1b",
        tertiary: "#735c00",
        "surface-tint": "#af2b3e",
        surface: "#fcf9f8",
        "on-error": "#ffffff",
        "on-primary-container": "#ff828a",
        "surface-bright": "#fcf9f8",
        "primary-container": "#800020",
        "tertiary-fixed-dim": "#e9c349",
        "crimson-dark": "#5B0016",
        "inverse-on-surface": "#f3f0ef",
        "surface-dim": "#dcd9d9",
        "on-secondary-fixed-variant": "#474744",
        "secondary-container": "#e1dfdc",
        "on-surface-variant": "#584141",
        "surface-container-high": "#eae7e7",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container": "#f0eded",
        "parchment-deep": "#F5F1E6",
        primary: "#570013",
        secondary: "#5e5e5c",
        "tertiary-container": "#cca730",
        "on-primary-fixed": "#40000b",
        "error-container": "#ffdad6",
        "charcoal-muted": "#333333",
        "primary-fixed": "#ffdada",
        "on-primary-fixed-variant": "#8e0f28",
        background: "#fcf9f8",
        "on-secondary-container": "#636360",
        "on-secondary-fixed": "#1b1c1a",
        "primary-fixed-dim": "#ffb3b5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "section-gap": "64px",
        "margin-mobile": "16px",
        gutter: "24px",
        "container-max": "1120px",
      },
      maxWidth: {
        "container-max": "1120px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"],
        hankenGrotesk: ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["EB Garamond", "serif"],
        "headline-sm": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "quote-display": ["EB Garamond", "serif"],
        aphorism: ["EB Garamond", "serif"],
        ebGaramond: ["EB Garamond", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "quote-display": ["22px", { lineHeight: "32px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        // Was referenced by templates/aphorisms.html but never defined, so
        // `text-aphorism` silently did nothing.
        aphorism: ["26px", { lineHeight: "40px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
