"""initial schema

Revision ID: f816b84ecd8c
Revises: 
Create Date: 2026-08-13 22:15:40.818082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f816b84ecd8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aphorisms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_handled'), ['handled'], unique=False)

    op.create_table('gloss_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=256), nullable=False),
    sa.Column('gloss', sa.Text(), nullable=False),
    sa.Column('is_phrase', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term', 'gloss', name='uq_gloss_term_gloss')
    )
    with op.batch_alter_table('gloss_terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gloss_terms_is_phrase'), ['is_phrase'], unique=False)
        batch_op.create_index(batch_op.f('ix_gloss_terms_term'), ['term'], unique=False)

    op.create_table('modern_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('strophe_start', sa.Integer(), nullable=True),
    sa.Column('strophe_end', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'chapter_id', name='uq_modern_chapter')
    )
    with op.batch_alter_table('modern_chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modern_chapters_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modern_chapters_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_modern_chapters_strophe_end'), ['strophe_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_modern_chapters_strophe_start'), ['strophe_start'], unique=False)

    op.create_table('shushaniki_glosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=256), nullable=False),
    sa.Column('gloss', sa.Text(), nullable=False),
    sa.Column('is_phrase', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term', 'gloss', name='uq_shushaniki_term_gloss')
    )
    with op.batch_alter_table('shushaniki_glosses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shushaniki_glosses_is_phrase'), ['is_phrase'], unique=False)
        batch_op.create_index(batch_op.f('ix_shushaniki_glosses_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_shushaniki_glosses_term'), ['term'], unique=False)

    op.create_table('shushaniki_main',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shushaniki_main', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shushaniki_main_chapter'), ['chapter'], unique=False)

    op.create_table('shushaniki_modern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shushaniki_modern', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shushaniki_modern_chapter_id'), ['chapter_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_at', sa.DateTime(), nullable=True),
    sa.Column('session_version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vefxistyaosani_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('strophe_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vefxistyaosani_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vefxistyaosani_lines_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vefxistyaosani_lines_strophe_id'), ['strophe_id'], unique=False)

    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('composed', sa.String(length=64), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('revision', sa.String(length=64), nullable=True),
    sa.Column('retrieved', sa.String(length=32), nullable=True),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_works_slug'), ['slug'], unique=True)

    op.create_table('gloss_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('strophe_global', sa.Integer(), nullable=False),
    sa.Column('strophe_local', sa.Integer(), nullable=True),
    sa.Column('ganm_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['gloss_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ganm_id', 'strophe_global', 'term_id', name='uq_gloss_occurrence')
    )
    with op.batch_alter_table('gloss_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gloss_occurrences_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gloss_occurrences_ganm_id'), ['ganm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gloss_occurrences_strophe_global'), ['strophe_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_gloss_occurrences_strophe_local'), ['strophe_local'], unique=False)
        batch_op.create_index(batch_op.f('ix_gloss_occurrences_term_id'), ['term_id'], unique=False)

    op.create_table('modern_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'section', name='uq_modern_section')
    )
    with op.batch_alter_table('modern_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modern_sections_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_modern_sections_work_id'), ['work_id'], unique=False)

    op.create_table('text_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('section_label', sa.String(length=32), nullable=True),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('unit_global', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_dialogue', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'unit_global', name='uq_text_unit_global')
    )
    with op.batch_alter_table('text_units', schema=None) as batch_op:
        batch_op.create_index('ix_text_unit_work_section', ['work_id', 'section'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_units_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_units_work_id'), ['work_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_units_work_id'))
        batch_op.drop_index(batch_op.f('ix_text_units_section'))
        batch_op.drop_index('ix_text_unit_work_section')

    op.drop_table('text_units')
    with op.batch_alter_table('modern_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modern_sections_work_id'))
        batch_op.drop_index(batch_op.f('ix_modern_sections_section'))

    op.drop_table('modern_sections')
    with op.batch_alter_table('gloss_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gloss_occurrences_term_id'))
        batch_op.drop_index(batch_op.f('ix_gloss_occurrences_strophe_local'))
        batch_op.drop_index(batch_op.f('ix_gloss_occurrences_strophe_global'))
        batch_op.drop_index(batch_op.f('ix_gloss_occurrences_ganm_id'))
        batch_op.drop_index(batch_op.f('ix_gloss_occurrences_chapter_id'))

    op.drop_table('gloss_occurrences')
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_works_slug'))

    op.drop_table('works')
    with op.batch_alter_table('vefxistyaosani_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vefxistyaosani_lines_strophe_id'))
        batch_op.drop_index(batch_op.f('ix_vefxistyaosani_lines_chapter_id'))

    op.drop_table('vefxistyaosani_lines')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('shushaniki_modern', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shushaniki_modern_chapter_id'))

    op.drop_table('shushaniki_modern')
    with op.batch_alter_table('shushaniki_main', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shushaniki_main_chapter'))

    op.drop_table('shushaniki_main')
    with op.batch_alter_table('shushaniki_glosses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shushaniki_glosses_term'))
        batch_op.drop_index(batch_op.f('ix_shushaniki_glosses_source'))
        batch_op.drop_index(batch_op.f('ix_shushaniki_glosses_is_phrase'))

    op.drop_table('shushaniki_glosses')
    with op.batch_alter_table('modern_chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modern_chapters_strophe_start'))
        batch_op.drop_index(batch_op.f('ix_modern_chapters_strophe_end'))
        batch_op.drop_index(batch_op.f('ix_modern_chapters_source'))
        batch_op.drop_index(batch_op.f('ix_modern_chapters_chapter_id'))

    op.drop_table('modern_chapters')
    with op.batch_alter_table('gloss_terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gloss_terms_term'))
        batch_op.drop_index(batch_op.f('ix_gloss_terms_is_phrase'))

    op.drop_table('gloss_terms')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_handled'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_email'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    op.drop_table('aphorisms')
    # ### end Alembic commands ###
